version: "1.2"
services:
  api-service:
    build: .
    restart: always
    ports:
      - 8090:8090
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true    
    depends_on:
      - mysqldb
      
  mysqldb:
    image: "mysql:8.0"
    volumes:
      - spring-db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: basics
      MYSQL_ROOT_PASSWORD: secret
volumes:
  spring-db:
